Liu x86 64
yaokai-liu/novice pull request #1
Opened 2024-06-05 02:51 UTC by yaokai-liu

Add x86_64 source files and workflow.

2024-06-05 09:29 UTC, KKiiim requested changes

2024-06-05 09:29 UTC, KKiiim commented on tests/testQuickSort.cpp
> +TEST(TestQuickSort1, TestQuickSort) {
It's TOO complex to test the customer qsort implementation.
May be just need to compare whether every member is larger(smaller) than the next one.

2024-06-05 09:38 UTC, KKiiim commented on tests/testAbs.cpp
> +    EXPECT_EQ(abs32(0), abs(0));
In test, need not to test `abs` in libc. Just expect(youfunc, 0)
Other test files are the same

2024-06-05 09:45 UTC, yaokai-liu commented on include/functions.h
> +void cqsort(void * const _nums, size_t _count, size_t _ele_size,
`cqsort` and `_sqort` are both aligned with standard C library function 
```
extern void qsort (void *__base, size_t __nmemb, size_t __size,
		   __compar_fn_t __compar) __nonnull ((1, 4));
```
in `stdlib.h`.
And implement within template is too hard for assembly.

2024-06-05 09:53 UTC, yaokai-liu commented on tests/testGetSum.cpp
> +    return s;
Maybe the value of `s` would be overflow out the max of  `int64_t`, but I think that should be handled by one who calls it.

2024-06-05 09:58 UTC, KKiiim commented on tests/testGetSum.cpp
> +    return s;
Of course the caller should understand . But if the return value is invalid, how can the caller know that the answer is wrong.

2024-06-05 09:58 UTC, KKiiim commented on csrc/cqsort.cpp
> +    char * base = (char *)alloca(_ele_size);
refactor and delete the multi `alloca`

2024-06-05 09:59 UTC, KKiiim commented on tests/testGetSum.cpp
> +    return s;
Which means, your api is unsafe and confused

2024-06-05 10:02 UTC, yaokai-liu commented on tests/testQuickSort.cpp
> +TEST(TestQuickSort1, TestQuickSort) {
an equivalent implementation of `int (*__compar_fn_t) (const void *, const void *)` which requested by `qsort` is like
```
int cmp (const void * a, const void *b) {
    return *(int64_t *)a - *(int64_t *)b;
};
```

Actually, any function with signature `int (*__compar_fn_t) (const void *, const void *)` and always return negative value while first param less than second param could be the `cmp`.

2024-06-05 10:11 UTC, KKiiim commented on tests/testQuickSort.cpp
> +TEST(TestQuickSort1, TestQuickSort) {
What you're saying is nothing to do with this comment

2024-06-06 02:21 UTC, KKiiim requested changes

2024-06-06 02:21 UTC, KKiiim commented on tests/testQuickSort.cpp
> +    for (int i = 0; i < BUFFER_LEN; i++){ buffer1[i] = BUFFER_LEN - i; buffer1[i] << shift; }
Does `buffer1[i] << shift` change any member's value?

2024-06-06 02:21 UTC, KKiiim commented on tests/testQuickSort.cpp
> +    for (int i = 0; i < BUFFER_LEN; i++){ buffer1[i] = value; }
Why should test qsort of an array which has all members the same.

2024-06-06 02:38 UTC, yaokai-liu commented on tests/testQuickSort.cpp
> +    for (int i = 0; i < BUFFER_LEN; i++){ buffer1[i] = value; }
To test an array all elements are the same.

2024-06-06 07:11 UTC, yaokai-liu commented on tests/testGetSum.cpp
> +    return s;
`cqsort` has been refactored with `cswap`.

2024-06-06 07:42 UTC, KKiiim approved these changes

2024-06-06 07:42 UTC, KKiiim commented on tests/testQuickSort.cpp
> +TEST(TestQuickSortReverseInt64Array, TestQuickSort) {
`random()` is a random number. Excluding meaningless performance expenses, what's the point of using `shift` for double randomization.

2024-06-06 08:37 UTC, merged