Liu aarch64
yaokai-liu/novice pull request #2
Opened 2024-06-05 09:06 UTC by yaokai-liu

Add aarch64 source files and workflow.

2024-06-05 09:35 UTC, KKiiim requested changes

2024-06-05 09:35 UTC, KKiiim commented on .github/workflows/.gitkeep
remove meaningless file

2024-06-06 02:32 UTC, yaokai-liu commented on .github/workflows/.gitkeep
folder keeper has been removed.

2024-06-06 07:47 UTC, KKiiim approved these changes

2024-06-06 07:47 UTC, KKiiim commented on csrc/cqsort.cpp
> +#include <alloca.h>
Delete these 13 lines.
Just include `functions.h`.

2024-06-06 08:11 UTC, yaokai-liu commented on csrc/cqsort.cpp
> +#include <alloca.h>
useless includes removed.

2024-06-06 08:38 UTC, merged